# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ziad/Documents/GitHub/File-Manager/FileMangerQT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ziad/Documents/GitHub/File-Manager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ziad/Documents/GitHub/File-Manager/CMakeFiles /home/ziad/Documents/GitHub/File-Manager//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ziad/Documents/GitHub/File-Manager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FileManger

# Build rule for target.
FileManger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FileManger
.PHONY : FileManger

# fast build rule for target.
FileManger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/build
.PHONY : FileManger/fast

#=============================================================================
# Target rules for targets named FileManger_autogen

# Build rule for target.
FileManger_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FileManger_autogen
.PHONY : FileManger_autogen

# fast build rule for target.
FileManger_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger_autogen.dir/build.make CMakeFiles/FileManger_autogen.dir/build
.PHONY : FileManger_autogen/fast

FileManger_autogen/mocs_compilation.o: FileManger_autogen/mocs_compilation.cpp.o
.PHONY : FileManger_autogen/mocs_compilation.o

# target to build an object file
FileManger_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/FileManger_autogen/mocs_compilation.cpp.o
.PHONY : FileManger_autogen/mocs_compilation.cpp.o

FileManger_autogen/mocs_compilation.i: FileManger_autogen/mocs_compilation.cpp.i
.PHONY : FileManger_autogen/mocs_compilation.i

# target to preprocess a source file
FileManger_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/FileManger_autogen/mocs_compilation.cpp.i
.PHONY : FileManger_autogen/mocs_compilation.cpp.i

FileManger_autogen/mocs_compilation.s: FileManger_autogen/mocs_compilation.cpp.s
.PHONY : FileManger_autogen/mocs_compilation.s

# target to generate assembly for a file
FileManger_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/FileManger_autogen/mocs_compilation.cpp.s
.PHONY : FileManger_autogen/mocs_compilation.cpp.s

controller.o: controller.cpp.o
.PHONY : controller.o

# target to build an object file
controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/controller.cpp.o
.PHONY : controller.cpp.o

controller.i: controller.cpp.i
.PHONY : controller.i

# target to preprocess a source file
controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/controller.cpp.i
.PHONY : controller.cpp.i

controller.s: controller.cpp.s
.PHONY : controller.s

# target to generate assembly for a file
controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/controller.cpp.s
.PHONY : controller.cpp.s

filecontentview.o: filecontentview.cpp.o
.PHONY : filecontentview.o

# target to build an object file
filecontentview.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/filecontentview.cpp.o
.PHONY : filecontentview.cpp.o

filecontentview.i: filecontentview.cpp.i
.PHONY : filecontentview.i

# target to preprocess a source file
filecontentview.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/filecontentview.cpp.i
.PHONY : filecontentview.cpp.i

filecontentview.s: filecontentview.cpp.s
.PHONY : filecontentview.s

# target to generate assembly for a file
filecontentview.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/filecontentview.cpp.s
.PHONY : filecontentview.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/main.cpp.s
.PHONY : main.cpp.s

view.o: view.cpp.o
.PHONY : view.o

# target to build an object file
view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/view.cpp.o
.PHONY : view.cpp.o

view.i: view.cpp.i
.PHONY : view.i

# target to preprocess a source file
view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/view.cpp.i
.PHONY : view.cpp.i

view.s: view.cpp.s
.PHONY : view.s

# target to generate assembly for a file
view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FileManger.dir/build.make CMakeFiles/FileManger.dir/view.cpp.s
.PHONY : view.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... FileManger_autogen"
	@echo "... FileManger"
	@echo "... FileManger_autogen/mocs_compilation.o"
	@echo "... FileManger_autogen/mocs_compilation.i"
	@echo "... FileManger_autogen/mocs_compilation.s"
	@echo "... controller.o"
	@echo "... controller.i"
	@echo "... controller.s"
	@echo "... filecontentview.o"
	@echo "... filecontentview.i"
	@echo "... filecontentview.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... view.o"
	@echo "... view.i"
	@echo "... view.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

